### ISSUE TITLE
Can't publish audio in remote

### ISSUE THREAD

**Issue by Kesha005** [porjo/babelcast#11]
Can't publish track when login  from remote device in network but works at localhost

**Comment by porjo** [comment]
If the client (publisher or subscriber) is behind certain kinds of NAT e.g. [CGNAT](https://en.wikipedia.org/wiki/Carrier-grade_NAT) then a [TURN server](https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT) is often required. Unlike STUN servers, TURN servers aren't usually available free of charge, so it would be up to you to find one and [modify Babelcast](https://github.com/porjo/babelcast/blob/e471f20d503ebaf81d67cb4b6b75158feed4c2b5/html/js/common.js#L75) to use it.

**Comment by porjo** [comment]
I just tested using latest version [v1.2.1](https://github.com/porjo/babelcast/releases/tag/v1.2.1) of Babelcast on a remote network and it works fine. Please test again using that version. If it still does not work, then perhaps one of the endpoints is behind something like CGNAT.

**Comment by Kesha005** [comment]
yes i fixed some bugs in nginx config it's works thanks bro
