### ISSUE TITLE
about recording `

### ISSUE THREAD

**Issue by Kesha005** [porjo/babelcast#15]
Pardon hi bro. How are you? I have some question. Can i record publishing data to local file such as mp3 or wav  format  & which package i can use ?
2. Do you have good book or article about pion/webrtc

**Comment by porjo** [comment]
Hi, I haven't tried recording before but it should be possible.

Some resources to check out: 
- Pion examples: https://github.com/pion/webrtc/blob/master/examples/README.md , see 'Save To Disk'
- book 'WebRTC For The Curious': https://webrtcforthecurious.com/

**Comment by Kesha005** [comment]
Thanks a lot
