### ISSUE TITLE
structur

### ISSUE THREAD

**Issue by Kesha005** [porjo/babelcast#20]
Pardon hi friend. Ho are you. I have some problems, if you have time you can help me.
How i can change project structure

You run chanell 

```
type Registry struct {
	sync.Mutex
	Channels map[string]*Channel
}
```

can i like

```
type Registry struct {
	sync.Mutex
	Channels map[int]map[string]*Channel
}
```

i have some event and in this event i should open chanell

**Comment by Kesha005** [comment]
int there EventId 

3:{"chanelname":*Chanell}

**Comment by porjo** [comment]
It is possible to change `Registry` in that way but whether that's the correct action will depend on what you're wanting to achieve. 

I'm sorry but I'm not in a position to provide general webrtc or Go programming advice.
