### ISSUE TITLE
about publisher

### ISSUE THREAD

**Issue by Kesha005** [porjo/babelcast#21]
hi friend how are you. I need help. How i can connect more than 1publisher in one channel.

**Comment by porjo** [comment]
Hi, having more than one publisher is not currently supported. It should be possible to do it - see [sfu-ws](https://github.com/pion/example-webrtc-applications/tree/master/sfu-ws) however I don't plan to add support to babelcast as it would add a lot of complexity.

**Comment by Kesha005** [comment]
aha thanks a lot friend  for advice. Good luck :)

вт, 29 окт. 2024 г., 04:12 Ian Bishop ***@***.***>:
