### ISSUE TITLE
[Feature Request] Repeater Server

### ISSUE THREAD

**Issue by teamcoltra** [porjo/babelcast#9]
Ian you fantastic human being. This is all I've been looking for for a week and you built it. A webRTC tool that was super lightweight that allows people to start channels and broadcast to them and other people can go listen to those channels. No video, no over the top UIs, just straightforward what I needed.

:P So as people do when they found the perfect lightweight thing they try to add features to it. 

What I want (and it's actually likely a whole second project) is I want the subscribers side of this, but I want it to listen to another babelcast server and just rebroadcast all the channels that it is producing. Basically a virtual machine running babelcast can support around 250 people but I want to be able to support about 500-1000 people. So my thoughts are have the initial babelcast server hanging out minding it's own business and then I can just create a second server. 

Looking at the code for this I'm sure I could probably sit down for day and start learning some Go maybe, it feels like exactly the right level of interesting/not-overly-complex first coding projects. However, I'm happy to pay you (and I'm happy to let you keep what you make me open source for other people to use too) since you probably already have an idea on how this would be done (and I do not). 

You don't have an email in your profile so hopefully this is appropriate here. Thanks so much!  Even if you can't help me this is amazing!

**Comment by porjo** [comment]
Hi, I'm glad you find it useful. Sorry but I don't have time to spend on coding this, but it's an interesting question to consider. I'm curious to know how you came up with the number of 250 for a virtual machine? I haven't done any load testing myself, but in theory cpu/memory usage should be minimal for each client as it's not doing any audio processing - it is just copying audio packets from input to output. It should be possible to serve thousands of clients on a not too beefy server. Bandwidth is easier to predict - it will be around 60kbps per client. I'm also curious to know more about your use-case - any more details you can share? :smile:

**Comment by teamcoltra** [comment]
Of course, and I'm likely hiring a developer to help me with this so I'll pass along any improvements I have to the code.

It's all CPU and I'm not sure where the CPU issues are coming from and my benchmarking was not super scientific but here's what I did:

![image](https://github.com/porjo/babelcast/assets/161164/da6e2159-adcc-4d0c-a58f-d5639a2aa01f)

I opened 30 chrome tabs at a time (lol but then I found out there is a limit in chrome to how many audio tabs, or webrtc tabs not sure, that you can have open at once so I switched to Edge) and kept watching TOP to see how the server reacted to it. It was adding about 12% when 30 tabs were loading at once and then 10-11% after it calmed down.  This was on a single core of a  Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz, What was crazy was I was hitting the CPU hard but at no point did ram go above 300MB for the whole server.   I do think I can get more juice out of it, this is on a testing server that I just have a ton of random crap installed to so I think there are some zombie processes involved because the load average was not coordinated well with CPU idle (but also CPU idle was not correlated well to actual live CPU usage). None the less if I can get 250 people on a $5 VM I can scale that well based on demand.

I also closed the whole window one at a time and it was dropping by the same amount so it at least directly correlates to the connections.  If this is some HTTP thing or something I'm not sure the cause.  

I'm totally happy to share the full details of the usecase after we launch (not because I don't want to share but because it's a client's job and I can't say). HOWEVER the gist is: 

We have a few locations who are broadcasting audio, think like a mall PA system. Then we have a bunch of people who want to tune into that broadcast at the mall they are in instead of listening to the PA. There are probably 100 malls across the globe (mostly the US) who would use our service and most malls have 100-200 listeners / patrons. Some malls have 10,000 listeners. 

I don't know why I went with mall, I could have said "think of something like twitch but for audio" or "radio stations", though our customer and the venue are in the same place (which is why I like WebRTC's low latency even when adding a server that's hundreds/thousands of KM away).

**Comment by porjo** [comment]
Hey, thanks for the insight into your testing. A couple of thoughts:
- I did a quick CPU profile using Go's built in tooling on babelcast itself and couldn't see a smoking gun to explain poor performance
- babelcast makes heavy use of concurrency (goroutines) so having multiple threads/cores available should help
- it would be interesting to run [sysbench](https://github.com/akopytov/sysbench) on your test server to see what kind of cpu performance you get and compare the result against a host with a newer CPU

The project sounds interesting - would definitely like to hear how you get on, and what solution you end up going with.

**Comment by teamcoltra** [comment]
For what it's worth, I don't think it is poor performance it matches up pretty closely with what I got out of Janus except a little better. Considering the test on Janus was just the echo test over and over again it should have a fairly low impact, so does this. I think just 250+ concurrent connections inherently has a tax.
